### ISSUE TITLE
[Request] Support git subdirectories

### ISSUE THREAD

**Issue by yefimtsev** [artem-y/commit#15]
Thanks for this tool, @artem-y!

One thing came to mind when I tried this - sometimes, users will spend most of their time not in the root of the git project.
Personally, I spend 99% of my time not in the root directory.
I guess it may be beneficial to provide a way to either choose a directory (e.g., via an argument) or, if possible, allow committing from subdirectories. I'm not familiar with **_go-git_** to comment on the second option.

What do you think?

**Comment by artem-y** [comment]
This is a good one, thanks for reporting!  
I've actually stumbled upon it myself too😅 
Definitely need to fix, I'll make it work from subdirectories.

**Comment by artem-y** [comment]
Closed the issue, it has now been fixed in version `v0.1.1`.  
Released in [v0.1.1: Support Subdirectories](https://github.com/artem-y/commit/releases/tag/v0.1.1).
